### ISSUE TITLE
np-laravel-plugin dependencies issue

### ISSUE THREAD

**Issue by adem82** [nbphpcouncil/nb-laravel-plugin#7]
I wanted to install the np laravel pluging. I got the following issues: I am using netbeans 8.0

Some plugins require plugin PHP Executable API to be installed.
The plugin PHP Executable API is requested in implementation version 201310111528.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin PHP Framework API to be installed.
The plugin PHP Framework API is requested in implementation version 201310111528.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin PHP Module API to be installed.
The plugin PHP Module API is requested in implementation version 201310111528.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin Composer to be installed.
The plugin Composer is requested in implementation version 201312091611.  The following plugin is affected:       Laravel4 Framework  Some plugins not installed to avoid potential installation problems.

**Comment by junichi11** [comment]
@adem82 
Sorry for inconvenience. 
I'll try to re-build a nbm in NetBeans 8.0. 

@jtakakura Could you create a new branch for NetBeans 8.0?

**Comment by junichi11** [comment]
@adem82 Could you try to use the following? :
https://github.com/nbphpcouncil/nb-laravel-plugin/releases/tag/v0.1.1 (org-nbphpcouncil-modules-php-laravel4-0.1.1-for-nb80.nbm)

**Comment by web-engineer** [comment]
I just tried this version and got the following -

<pre>
Some plugins require plugin PHP Executable API to be installed.
The plugin PHP Executable API is requested in implementation version 201310111528.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin PHP Framework API to be installed.
The plugin PHP Framework API is requested in implementation version 201310111528.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin PHP Module API to be installed.
The plugin PHP Module API is requested in implementation version 201310111528.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin Composer to be installed.
The plugin Composer is requested in implementation version 201312091611.  The following plugin is affected:       Laravel4 Framework  Some plugins not installed to avoid potential installation problems.</pre>

**Comment by junichi11** [comment]
@web-engineer 
What is your NetBeans version? Please try to look at help > version information
e.g. NetBeans IDE 8.0 (Build 201403101706)

**Comment by web-engineer** [comment]
NetBeans IDE 8.0 (Build 201403101706)

**Comment by junichi11** [comment]
I can't reproduce it. Did you download org-nbphpcouncil-modules-php-laravel4-0.1.1-for-**nb80**.nbm?

**Comment by web-engineer** [comment]
My plugins installed include the following, the missing plugins reported by your plugin are not available as far as I can see from the mainstream plugin sources. Is it a case of importing these from somewhere else? Or should they have been packaged together?

![screen shot 2014-07-16 at 12 11 25](https://cloud.githubusercontent.com/assets/230107/3597911/fcdab93e-0cd9-11e4-8c5c-3fad19b3e3ef.png)

**Comment by web-engineer** [comment]
> I can't reproduce it. Did you download org-nbphpcouncil-modules-php-laravel4-0.1.1-for-nb80.nbm?

Yes - this is the file I installed from your releases link. 

Is this just a case of adding php executable/composer plugins? If so - which source should we be using?

**Comment by web-engineer** [comment]
I've tried downloading manually and by using the repo - my selected repositories look as follows -
![screen shot 2014-07-16 at 12 14 54](https://cloud.githubusercontent.com/assets/230107/3597938/75cb19b0-0cda-11e4-8e0d-b210e45785d7.png)

**Comment by junichi11** [comment]
> I've tried downloading manually and by using the repo - my selected repositories look as follows -

It doesn't work (isn't available) since it's too old.

**Comment by junichi11** [comment]
Could you try to update NetBeans? (Is your version patch2?)

**Comment by web-engineer** [comment]
OK - tried updating, no update available, getting a fresh copy from netbeans.org to make sure I've got the current release, it is concievable that I may have a "pre release" version installed... Will let you know how i get on...

**Comment by junichi11** [comment]
It seems that you are using a nbm for other version because your error message is the same as first reporter.  
There are 3 nbms in releases.
https://github.com/nbphpcouncil/nb-laravel-plugin/releases/tag/v0.1.1
- org-nbphpcouncil-modules-php-laravel4-0.1.1-for-nb74-201312091611.nbm
- org-nbphpcouncil-modules-php-laravel4-0.1.1-for-nb74.nbm
- org-nbphpcouncil-modules-php-laravel4-0.1.1-for-nb80.nbm (use this)

**Comment by web-engineer** [comment]
Very strange... I installed the latest netbeans, this install failed - not sure why... saw your message and retried again (i'm positive I tried the same link before....) and the plugin installed. 

I can only think that the install I have was or is in some way broken and that re-installing has put the packages your plugin needs in place an it now installs...

The version of nb available on their site currenty seems to download as 
NetBeans IDE 8.0 RC1 (Build 201402242200)
Probably because this is older than my current installation its causing the installer a problem (i just renamed the app before install).

<pre>Updating this version took it to 
Product Version: NetBeans IDE 8.0 RC1 (Build 201402242200)
Updates: NetBeans IDE is updated to version NetBeans 8.0 Patch 2
Java: 1.7.0_45; Java HotSpot(TM) 64-Bit Server VM 24.45-b08
Runtime: Java(TM) SE Runtime Environment 1.7.0_45-b18
System: Mac OS X version 10.9.4 running on x86_64; UTF-8; en_US (nb)
User directory: /Users/Craig/Library/Application Support/NetBeans/8.0rc1
Cache directory: /Users/Craig/Library/Caches/NetBeans/8.0rc1</pre>

Compared to my previous install

<pre>Product Version: NetBeans IDE 8.0 (Build 201403101706)
Updates: NetBeans IDE is updated to version NetBeans 8.0 Patch 2
Java: 1.7.0_45; Java HotSpot(TM) 64-Bit Server VM 24.45-b08
Runtime: Java(TM) SE Runtime Environment 1.7.0_45-b18
System: Mac OS X version 10.9.4 running on x86_64; UTF-8; en_US (nb)
User directory: /Users/Craig/Library/Application Support/NetBeans/8.0
Cache directory: /Users/Craig/Library/Caches/NetBeans/8.0</pre>

Both are reporting the same "patch 2" update release though the build looks older on the current public release to the one I was using, suspect I either installed this early or Oracle have pulled this version from release.

Moral of the story - looks like this isn't you guys - an issue with netbeans versions! Given you all the details though incase this helps someone else with the same problem... re-install from netbeans.org seems to do the trick!

**Comment by junichi11** [comment]
Well...  You were able to install this plugin, weren't you?
Unfortunately, this depends on build version of NetBeans because this plugin is using implementation version for PHP apis. We can improve this problem in NB80. I asked that author of this plugin before. If it's not fixed, I'll try to ask again.

Thanks.

**Comment by ladame** [comment]
I don't know how to install this plugin after I downloaded it. Where is the "Plugin distribution files (*.nbm)" located ? I use NetBeans for linux and download tar.gz

**Comment by junichi11** [comment]
@ladame Please have a look at the `Tools > Plugin`

**Comment by karolymarton** [comment]
I have this problem too. (NB 8.0.1 / 201408251540)

**Comment by junichi11** [comment]
@mdesign83 What's the version number of plugin? Could you try to install the following? https://github.com/nbphpcouncil/nb-laravel-plugin/releases/tag/v0.1.2

**Comment by karolymarton** [comment]
Dear @junichi11 It was v.0.1.1, v0.1.2 works! Thank you for the link.

**Comment by junichi11** [comment]
@mdesign83 You are welcome :)
